package io.github.abc15018045126.sora.lang.analysis

import android.os.Bundle
import io.github.abc15018045126.sora.text.CharPosition
import io.github.abc15018045126.sora.text.ContentReference

/**
 * AnalyzeManager receives text updates and do its work to start lexers/parsers to analyze the code
 * so that we can provide syntax-highlighting and exact auto-completion.
 *
 * @author abc15018045126
 */
interface AnalyzeManager {

    /**
     * Set the span receiver of the manager.
     *
     * This is called when the [io.github.abc15018045126.sora.lang.Language] is going to be used by
     * an editor. It will also be called when the instance is no longer used.
     * Make sure you check the exact receiver at the time you send results to it.
     * Thus, you should save the instance at your side.
     */
    var receiver: StyleReceiver?

    /**
     * Called when new text is set in editor by either [io.github.abc15018045126.sora.widget.CodeEditor.setText]
     * or [io.github.abc15018045126.sora.widget.CodeEditor.setText].
     *
     * @param content        New text, read-only. Accesses to it are not validated. It is not recommended saving
     * this object for reading. You can make a copy of the text and update it. But for
     * memory saving, you may want to store it.
     * @param extraArguments Arguments set by [io.github.abc15018045126.sora.widget.CodeEditor.setText]
     */
    fun reset(content: ContentReference, extraArguments: Bundle)

    /**
     * The [ContentReference] set by [reset] has inserted
     * text with the given position and text.
     *
     * @param start           The insertion start
     * @param end             The insertion end
     * @param insertedContent The content inserted
     */
    fun insert(start: CharPosition, end: CharPosition, insertedContent: CharSequence)

    /**
     * The [ContentReference] set by [reset] has deleted
     * text with the given position and text.
     *
     * @param start          The deletion start
     * @param end            The deletion end
     * @param deletedContent The text deleted. Generated by [io.github.abc15018045126.sora.text.Content] object.
     */
    fun delete(start: CharPosition, end: CharPosition, deletedContent: CharSequence)

    /**
     * Rerun the analysis forcibly
     */
    fun rerun()

    /**
     * Destroy the manager. Release any resources held.
     * Make sure that you will not call the receiver anymore.
     */
    fun destroy()

}
