package io.github.abc15018045126.sora.text

import io.github.abc15018045126.sora.annotations.UnsupportedUserUsage

/**
 * This is the listener for content.
 * You will receive calls when the Content object is going to change or changed.
 *
 * @author abc15018045126
 */
interface ContentListener {

    /**
     * This is to notify you that you will receive [ContentListener.afterDelete]
     * and [ContentListener.afterInsert] calls.
     * These two calls are an action of replacement.
     * ** You are not expected to make changes to this Content object at this method. **
     *
     * @param content The target Content object being replaced text
     */
    fun beforeReplace(content: Content)

    /**
     * This is to notify you that the given Content object has inserted text with the given position and text
     *
     * @param content         The Content which has inserted the given text
     * @param startLine       The insertion position line
     * @param startColumn     The insertion position column on the line
     * @param endLine         The line position of the last character in inserted content
     * @param endColumn       The column position after the last character in inserted content
     * @param insertedContent The content inserted
     */
    fun afterInsert(
        content: Content,
        startLine: Int,
        startColumn: Int,
        endLine: Int,
        endColumn: Int,
        insertedContent: CharSequence
    )

    /**
     * This is to notify you that the Content object has deleted the text with the given position.
     *
     * @param content        The Content which has deleted text
     * @param startLine      The start line of deleted text
     * @param startColumn    The start column of deleted text
     * @param endLine        The end line of deleted text
     * @param endColumn      The end column of deleted text(But this character not deleted)
     * @param deletedContent The text deleted.Generated by Content object.
     */
    fun afterDelete(
        content: Content,
        startLine: Int,
        startColumn: Int,
        endLine: Int,
        endColumn: Int,
        deletedContent: CharSequence
    )

    /**
     * Internal API
     */
    @UnsupportedUserUsage
    fun beforeModification(content: Content) {
    }
}
